
import java.awt.*;
import static java.awt.Color.*;
import java.awt.event.*;

/**
 * TIC TAC TOE!
 * @author Billy Andrews
 * @version 3.1
 */
public class TTT extends javax.swing.JFrame implements ActionListener {

    boolean xGoesFirst = true;
    boolean competitiveMode = true;
    boolean player1Turn = true;
    boolean SinglePlayerMode = true;
    static int playerXScore = 0;
    static int playerOScore = 0;
    static int playerTScore = 0;
    static char but1 = '\u0000';
    static char but2 = '\u0000';
    static char but3 = '\u0000';
    static char but4 = '\u0000';
    static char but5 = '\u0000';
    static char but6 = '\u0000';
    static char but7 = '\u0000';
    static char but8 = '\u0000';
    static char but9 = '\u0000';


    /**
     * Creates new form TTT
     */
    public TTT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOScore = new javax.swing.JLabel();
        jLabelXScore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTScore = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jLabelInfoBar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jRadioButton1P = new javax.swing.JRadioButton();
        jRadioButton2P = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TTT");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tic Tac Toe", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("O");

        jLabelOScore.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelOScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOScore.setText("0");

        jLabelXScore.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelXScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelXScore.setText("0");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIES");

        jLabelTScore.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTScore.setText("0");

        jButtonClear.setText("Clear Board");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelXScore, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabelTScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelOScore, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelXScore)
                    .addComponent(jLabelOScore)
                    .addComponent(jLabelTScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClear))
        );

        jLabelInfoBar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelInfoBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfoBar.setText("X's turn!");
        jLabelInfoBar.setToolTipText("");
        jLabelInfoBar.setFocusable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setToolTipText("");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset Scores");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jRadioButton1P.setSelected(true);
        jRadioButton1P.setText("1 Player");
        jRadioButton1P.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1PStateChanged(evt);
            }
        });
        jRadioButton1P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1PActionPerformed(evt);
            }
        });

        jRadioButton2P.setText("2 Players");
        jRadioButton2P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2PActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("CPU Competitive Mode");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton1P)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2P))
                    .addComponent(jButtonExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1P)
                    .addComponent(jRadioButton2P))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInfoBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("TicTacToePanel");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The code to make the game 1-Player mode.
     */
    public void computerGo() {
        String[] buttonListStrings = {jButton1.getText(), jButton2.getText(), jButton3.getText(),
                jButton4.getText(), jButton5.getText(), jButton6.getText(),
                jButton7.getText(), jButton8.getText(), jButton9.getText()};
        int rando = 1 + (int) (Math.random() * ((9 - 1) + 1));
        //System.out.print(rando);
        if (competitiveMode == false) {
            if (!"".equals(buttonListStrings[rando - 1])) {
                computerGo();
            } else {
                switch (rando) {
                    case 1:
                        jButton1.doClick(250);
                        break;
                    case 2:
                        jButton2.doClick(250);
                        break;
                    case 3:
                        jButton3.doClick(250);
                        break;
                    case 4:
                        jButton4.doClick(250);
                        break;
                    case 5:
                        jButton5.doClick(250);
                        break;
                    case 6:
                        jButton6.doClick(250);
                        break;
                    case 7:
                        jButton7.doClick(250);
                        break;
                    case 8:
                        jButton8.doClick(250);
                        break;
                    case 9:
                        jButton9.doClick(250);
                        break;
                }
                player1Turn = true;
            }
        } else {
            // if COMPETITIVE MODE is true.........
            if (!"".equals(buttonListStrings[rando - 1])) {
                computerGo(); 
            } else if (but1 == '\u0000' && but2 == '\u0000' && but3 == '\u0000' &&
                    but4 == '\u0000' && but5 == '\u0000' && but6 == '\u0000' && 
                    but7 == '\u0000' && but8 == '\u0000' && but9 == '\u0000'){
                    switch (rando) {
                    case 1:
                        jButton1.doClick(250);
                        break;
                    case 2:
                        jButton2.doClick(250);
                        break;
                    case 3:
                        jButton3.doClick(250);
                        break;
                    case 4:
                        jButton4.doClick(250);
                        break;
                    case 5:
                        jButton5.doClick(250);
                        break;
                    case 6:
                        jButton6.doClick(250);
                        break;
                    case 7:
                        jButton7.doClick(250);
                        break;
                    case 8:
                        jButton8.doClick(250);
                        break;
                    case 9:
                        jButton9.doClick(250);
                        break;
                }
            } else if (but1 == 'o' && but2 == 'o' && but3 == '\u0000') {
                jButton3.doClick(250);
            } else if (but1 == 'o' && but2 == '\u0000' && but3 == 'o') {
                jButton2.doClick(250);
            } else if (but1 == '\u0000' && but2 == 'o' && but3 == 'o') {
                jButton1.doClick(250);
            } else if (but4 == '\u0000' && but5 == 'o' && but6 == 'o') {
                jButton4.doClick(250);
            } else if (but4 == 'o' && but5 == '\u0000' && but6 == 'o') {
                jButton5.doClick(250);
            } else if (but4 == 'o' && but5 == 'o' && but6 == '\u0000') {
                jButton6.doClick(250);
            } else if (but7 == '\u0000' && but8 == 'o' && but9 == 'o') {
                jButton7.doClick(250);
            } else if (but7 == 'o' && but8 == '\u0000' && but9 == 'o') {
                jButton8.doClick(250);
            } else if (but7 == 'o' && but8 == 'o' && but9 == '\u0000') {
                jButton9.doClick(250);
            } else if (but1 == '\u0000' && but4 == 'o' && but7 == 'o') {
                jButton1.doClick(250);
            } else if (but1 == 'o' && but4 == '\u0000' && but7 == 'o') {
                jButton4.doClick(250);
            } else if (but1 == 'o' && but4 == 'o' && but7 == '\u0000') {
                jButton7.doClick(250);
            } else if (but2 == '\u0000' && but5 == 'o' && but8 == 'o') {
                jButton2.doClick(250);
            } else if (but2 == 'o' && but5 == '\u0000' && but8 == 'o') {
                jButton5.doClick(250);
            } else if (but2 == 'o' && but5 == 'o' && but8 == '\u0000') {
                jButton8.doClick(250);
            } else if (but3 == '\u0000' && but6 == 'o' && but9 == 'o') {
                jButton3.doClick(250);
            } else if (but3 == 'o' && but6 == '\u0000' && but9 == 'o') {
                jButton6.doClick(250);
            } else if (but3 == 'o' && but6 == 'o' && but9 == '\u0000') {
                jButton9.doClick(250);
            } else if (but1 == '\u0000' && but5 == 'o' && but9 == 'o') {
                jButton1.doClick(250);
            } else if (but1 == 'o' && but5 == '\u0000' && but9 == 'o') {
                jButton5.doClick(250);
            } else if (but1 == 'o' && but5 == 'o' && but9 == '\u0000') {
                jButton9.doClick(250);
            } else if (but7 == '\u0000' && but5 == 'o' && but3 == 'o') {
                jButton7.doClick(250);
            } else if (but7 == 'o' && but5 == '\u0000' && but3 == 'o') {
                jButton5.doClick(250);
            } else if (but7 == 'o' && but5 == 'o' && but3 == '\u0000') {
   // If the CPU can block the PLAYER from winning:           
                jButton3.doClick(250);
            } else if (but1 == 'x' && but2 == 'x' && but3 == '\u0000') {
                jButton3.doClick(250);
            } else if (but1 == 'x' && but2 == '\u0000' && but3 == 'x') {
                jButton2.doClick(250);
            } else if (but1 == '\u0000' && but2 == 'x' && but3 == 'x') {
                jButton1.doClick(250);
            } else if (but4 == '\u0000' && but5 == 'x' && but6 == 'x') {
                jButton4.doClick(250);
            } else if (but4 == 'x' && but5 == '\u0000' && but6 == 'x') {
                jButton5.doClick(250);
            } else if (but4 == 'x' && but5 == 'x' && but6 == '\u0000') {
                jButton6.doClick(250);
            } else if (but7 == '\u0000' && but8 == 'x' && but9 == 'x') {
                jButton7.doClick(250);
            } else if (but7 == 'x' && but8 == '\u0000' && but9 == 'x') {
                jButton8.doClick(250);
            } else if (but7 == 'x' && but8 == 'x' && but9 == '\u0000') {
                jButton9.doClick(250);
            } else if (but1 == '\u0000' && but4 == 'x' && but7 == 'x') {
                jButton1.doClick(250);
            } else if (but1 == 'x' && but4 == '\u0000' && but7 == 'x') {
                jButton4.doClick(250);
            } else if (but1 == 'x' && but4 == 'x' && but7 == '\u0000') {
                jButton7.doClick(250);
            } else if (but2 == '\u0000' && but5 == 'x' && but8 == 'x') {
                jButton2.doClick(250);
            } else if (but2 == 'x' && but5 == '\u0000' && but8 == 'x') {
                jButton5.doClick(250);
            } else if (but2 == 'x' && but5 == 'x' && but8 == '\u0000') {
                jButton8.doClick(250);
            } else if (but3 == '\u0000' && but6 == 'x' && but9 == 'x') {
                jButton3.doClick(250);
            } else if (but3 == 'x' && but6 == '\u0000' && but9 == 'x') {
                jButton6.doClick(250);
            } else if (but3 == 'x' && but6 == 'x' && but9 == '\u0000') {
                jButton9.doClick(250);
            } else if (but1 == '\u0000' && but5 == 'x' && but9 == 'x') {
                jButton1.doClick(250);
            } else if (but1 == 'x' && but5 == '\u0000' && but9 == 'x') {
                jButton5.doClick(250);
            } else if (but1 == 'x' && but5 == 'x' && but9 == '\u0000') {
                jButton9.doClick(250);
            } else if (but7 == '\u0000' && but5 == 'x' && but3 == 'x') {
                jButton7.doClick(250);
            } else if (but7 == 'x' && but5 == '\u0000' && but3 == 'x') {
                jButton5.doClick(250);
            } else if (but7 == 'x' && but5 == 'x' && but3 == '\u0000') {
    // If there are two open spaces:
                jButton3.doClick(250);
            } else if (but1 == 'o' && but2 == '\u0000' && but3 == '\u0000') {
                if (rando%2==1)
                    jButton3.doClick(250);
                else
                    jButton2.doClick(250);
            } else if (but1 == '\u0000' && but2 == '\u0000' && but3 == 'o') {
                if (rando%2==1)
                    jButton2.doClick(250);
                else
                    jButton1.doClick(250);
            } else if (but1 == '\u0000' && but2 == 'o' && but3 == '\u0000') {
                if (rando%2==1)
                    jButton1.doClick(250);
                else
                    jButton3.doClick(250);
            } else if (but4 == '\u0000' && but5 == '\u0000' && but6 == 'o') {
                if (rando%2==1)
                    jButton4.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but4 == 'o' && but5 == '\u0000' && but6 == '\u0000') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton6.doClick(250);
            } else if (but4 == '\u0000' && but5 == 'o' && but6 == '\u0000') {
                if (rando%2==1)
                    jButton6.doClick(250);
                else
                    jButton4.doClick(250);
            } else if (but7 == '\u0000' && but8 == '\u0000' && but9 == 'o') {
                if (rando%2==1)
                    jButton7.doClick(250);
                else
                    jButton8.doClick(250);
            } else if (but7 == 'o' && but8 == '\u0000' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton8.doClick(250);
                else
                    jButton9.doClick(250);
            } else if (but7 == '\u0000' && but8 == 'o' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton9.doClick(250);
                else
                    jButton7.doClick(250);
            } else if (but1 == '\u0000' && but4 == 'o' && but7 == '\u0000') {
                if (rando%2==1)
                    jButton1.doClick(250);
                else
                    jButton7.doClick(250);
            } else if (but1 == '\u0000' && but4 == '\u0000' && but7 == 'o') {
                if (rando%2==1)
                    jButton4.doClick(250);
                else
                    jButton1.doClick(250);
            } else if (but1 == 'o' && but4 == '\u0000' && but7 == '\u0000') {
                if (rando%2==1)
                    jButton7.doClick(250);
                else
                    jButton4.doClick(250);
            } else if (but2 == '\u0000' && but5 == 'o' && but8 == '\u0000') {
                if (rando%2==1)
                    jButton2.doClick(250);
                else
                    jButton8.doClick(250);
            } else if (but2 == '\u0000' && but5 == '\u0000' && but8 == 'o') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton2.doClick(250);
            } else if (but2 == 'o' && but5 == '\u0000' && but8 == '\u0000') {
                if (rando%2==1)
                    jButton8.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but3 == '\u0000' && but6 == 'o' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton3.doClick(250);
                else
                    jButton9.doClick(250);
            } else if (but3 == '\u0000' && but6 == '\u0000' && but9 == 'o') {
                if (rando%2==1)
                    jButton6.doClick(250);
                else
                    jButton3.doClick(250);
            } else if (but3 == 'o' && but6 == '\u0000' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton9.doClick(250);
                else
                    jButton6.doClick(250);
            } else if (but1 == '\u0000' && but5 == '\u0000' && but9 == 'o') {
                if (rando%2==1)
                    jButton1.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but1 == 'o' && but5 == '\u0000' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton9.doClick(250);
            } else if (but1 == '\u0000' && but5 == 'o' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton9.doClick(250);
                else
                    jButton1.doClick(250);
            } else if (but7 == '\u0000' && but5 == '\u0000' && but3 == 'o') {
                if (rando%2==1)
                    jButton7.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but7 == '\u0000' && but5 == '\u0000' && but3 == 'o') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton7.doClick(250);
            } else if (but7 == 'o' && but5 == '\u0000' && but3 == '\u0000') {
                if (rando%2==1)
                    jButton3.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but1 == 'x' && but2 == '\u0000' && but3 == '\u0000') {
                if (rando%2==1)
                    jButton3.doClick(250);
                else
                    jButton2.doClick(250);
            } else if (but1 == '\u0000' && but2 == '\u0000' && but3 == 'x') {
                if (rando%2==1)
                    jButton2.doClick(250);
                else
                    jButton1.doClick(250);
            } else if (but1 == '\u0000' && but2 == 'x' && but3 == '\u0000') {
                if (rando%2==1)
                    jButton1.doClick(250);
                else
                    jButton3.doClick(250);
            } else if (but4 == '\u0000' && but5 == '\u0000' && but6 == 'x') {
                if (rando%2==1)
                    jButton4.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but4 == 'x' && but5 == '\u0000' && but6 == '\u0000') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton6.doClick(250);
            } else if (but4 == '\u0000' && but5 == 'x' && but6 == '\u0000') {
                if (rando%2==1)
                    jButton6.doClick(250);
                else
                    jButton4.doClick(250);
            } else if (but7 == '\u0000' && but8 == '\u0000' && but9 == 'x') {
                if (rando%2==1)
                    jButton7.doClick(250);
                else 
                    jButton8.doClick(250);
            } else if (but7 == 'x' && but8 == '\u0000' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton8.doClick(250);
                else
                    jButton9.doClick(250);
            } else if (but7 == '\u0000' && but8 == 'x' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton9.doClick(250);
                else
                    jButton7.doClick(250);
            } else if (but1 == '\u0000' && but4 == 'x' && but7 == '\u0000') {
                if (rando%2==1)
                    jButton1.doClick(250);
                else
                    jButton7.doClick(250);
            } else if (but1 == '\u0000' && but4 == '\u0000' && but7 == 'x') {
                if (rando%2==1)
                    jButton4.doClick(250);
                else
                    jButton1.doClick(250);
            } else if (but1 == 'x' && but4 == '\u0000' && but7 == '\u0000') {
                if (rando%2==1)
                    jButton7.doClick(250);
                else
                    jButton4.doClick(250);
            } else if (but2 == '\u0000' && but5 == 'x' && but8 == '\u0000') {
                if (rando%2==1)
                    jButton2.doClick(250);
                else
                    jButton8.doClick(250);
            } else if (but2 == '\u0000' && but5 == '\u0000' && but8 == 'x') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton2.doClick(250);
            } else if (but2 == 'x' && but5 == '\u0000' && but8 == '\u0000') {
                if (rando%2==1)
                    jButton8.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but3 == '\u0000' && but6 == 'x' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton3.doClick(250);
                else
                    jButton9.doClick(250);
            } else if (but3 == '\u0000' && but6 == '\u0000' && but9 == 'x') {
                if (rando%2==1)
                    jButton6.doClick(250);
                else
                    jButton3.doClick(250);
            } else if (but3 == 'x' && but6 == '\u0000' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton9.doClick(250);
                else
                    jButton6.doClick(250);
            } else if (but1 == '\u0000' && but5 == '\u0000' && but9 == 'x') {
                if (rando%2==1)
                    jButton1.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but1 == 'x' && but5 == '\u0000' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton9.doClick(250);
            } else if (but1 == '\u0000' && but5 == 'x' && but9 == '\u0000') {
                if (rando%2==1)
                    jButton9.doClick(250);
                else
                    jButton1.doClick(250);
            } else if (but7 == '\u0000' && but5 == '\u0000' && but3 == 'x') {
                if (rando%2==1)
                    jButton7.doClick(250);
                else
                    jButton5.doClick(250);
            } else if (but7 == '\u0000' && but5 == '\u0000' && but3 == 'x') {
                if (rando%2==1)
                    jButton5.doClick(250);
                else
                    jButton7.doClick(250);
            } else if (but7 == 'x' && but5 == '\u0000' && but3 == '\u0000') {
                if (rando%2==1)
                    jButton3.doClick(250);
                else
                    jButton5.doClick(250);
            }
            player1Turn = true;
        }
    }

    /**
     * Keeps track of who's turn it is.
     */
    public void changeFirstPlayer() {
        if (xGoesFirst) {
            xGoesFirst = false;
        } else {
            xGoesFirst = true;
        }
    }

    /**
     * Changes the button's colors if triple is a winner
     */
    public void changeButtonColor() {
        if (but1 == 'x' && but2 == 'x' && but3 == 'x') {
            jButton1.setForeground(RED);
            jButton2.setForeground(RED);
            jButton3.setForeground(RED);
        } else if (but4 == 'x' && but5 == 'x' && but6 == 'x') {
            jButton4.setForeground(RED);
            jButton5.setForeground(RED);
            jButton6.setForeground(RED);
        } else if (but7 == 'x' && but8 == 'x' && but9 == 'x') {
            jButton7.setForeground(RED);
            jButton8.setForeground(RED);
            jButton9.setForeground(RED);
        } else if (but1 == 'x' && but4 == 'x' && but7 == 'x') {
            jButton1.setForeground(RED);
            jButton4.setForeground(RED);
            jButton7.setForeground(RED);
        } else if (but2 == 'x' && but5 == 'x' && but8 == 'x') {
            jButton2.setForeground(RED);
            jButton5.setForeground(RED);
            jButton8.setForeground(RED);
        } else if (but3 == 'x' && but6 == 'x' && but9 == 'x') {
            jButton3.setForeground(RED);
            jButton6.setForeground(RED);
            jButton9.setForeground(RED);
        } else if (but1 == 'x' && but5 == 'x' && but9 == 'x') {
            jButton1.setForeground(RED);
            jButton5.setForeground(RED);
            jButton9.setForeground(RED);
        } else if (but7 == 'x' && but5 == 'x' && but3 == 'x') {
            jButton7.setForeground(RED);
            jButton5.setForeground(RED);
            jButton3.setForeground(RED);
        } else if (but1 == 'o' && but2 == 'o' && but3 == 'o') {
            jButton1.setForeground(BLUE);
            jButton2.setForeground(BLUE);
            jButton3.setForeground(BLUE);
        } else if (but4 == 'o' && but5 == 'o' && but6 == 'o') {
            jButton4.setForeground(BLUE);
            jButton5.setForeground(BLUE);
            jButton6.setForeground(BLUE);
        } else if (but7 == 'o' && but8 == 'o' && but9 == 'o') {
            jButton7.setForeground(BLUE);
            jButton8.setForeground(BLUE);
            jButton9.setForeground(BLUE);
        } else if (but1 == 'o' && but4 == 'o' && but7 == 'o') {
            jButton1.setForeground(BLUE);
            jButton4.setForeground(BLUE);
            jButton7.setForeground(BLUE);
        } else if (but2 == 'o' && but5 == 'o' && but8 == 'o') {
            jButton2.setForeground(BLUE);
            jButton5.setForeground(BLUE);
            jButton8.setForeground(BLUE);
        } else if (but3 == 'o' && but6 == 'o' && but9 == 'o') {
            jButton3.setForeground(BLUE);
            jButton6.setForeground(BLUE);
            jButton9.setForeground(BLUE);
        } else if (but1 == 'o' && but5 == 'o' && but9 == 'o') {
            jButton1.setForeground(BLUE);
            jButton5.setForeground(BLUE);
            jButton9.setForeground(BLUE);
        } else if (but7 == 'o' && but5 == 'o' && but3 == 'o') {
            jButton7.setForeground(BLUE);
            jButton5.setForeground(BLUE);
            jButton3.setForeground(BLUE);
        }
    }

    /**
     * Disables the board's buttons.
     */
    public void disableButtons() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButtonClear.setBackground(GREEN);
    }

    /**
     * Resets the colors and clears the board.
     */
    public void reset() {

        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        jButton1.setForeground(BLACK);
        jButton2.setForeground(BLACK);
        jButton3.setForeground(BLACK);
        jButton4.setForeground(BLACK);
        jButton5.setForeground(BLACK);
        jButton6.setForeground(BLACK);
        jButton7.setForeground(BLACK);
        jButton8.setForeground(BLACK);
        jButton9.setForeground(BLACK);
        jButtonClear.setBackground(jButtonReset.getBackground());
        but1 = '\u0000';
        but2 = '\u0000';
        but3 = '\u0000';
        but4 = '\u0000';
        but5 = '\u0000';
        but6 = '\u0000';
        but7 = '\u0000';
        but8 = '\u0000';
        but9 = '\u0000';
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
    }

    // Menu buttons

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        reset();
        if (SinglePlayerMode) {
            player1Turn = xGoesFirst == true;
        } else {
            player1Turn = xGoesFirst == false;
        }

        if (player1Turn = xGoesFirst == true) {
            jLabelInfoBar.setText("X's turn!");
        } else {
            jLabelInfoBar.setText("O's turn!");
            if (SinglePlayerMode) {
                computerGo();
            }
        }


    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        reset();
        playerXScore = 0;
        playerOScore = 0;
        playerTScore = 0;
        jLabelXScore.setText(String.valueOf(playerXScore));
        jLabelOScore.setText(String.valueOf(playerOScore));
        jLabelTScore.setText(String.valueOf(playerTScore));
    }//GEN-LAST:event_jButtonResetActionPerformed

    // Board buttons

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jButton1.getText() == "") {
            if (player1Turn == true) {
                jButton1.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but1 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                    disableButtons();
                    changeFirstPlayer();
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton1.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but1 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jButton2.getText() == "") {
            if (player1Turn == true) {
                jButton2.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but2 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton2.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but2 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jButton3.getText() == "") {
            if (player1Turn == true) {
                jButton3.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but3 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton3.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but3 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jButton4.getText() == "") {
            if (player1Turn == true) {
                jButton4.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but4 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton4.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but4 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jButton5.getText() == "") {
            if (player1Turn == true) {
                jButton5.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but5 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton5.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but5 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (jButton6.getText() == "") {
            if (player1Turn == true) {
                jButton6.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but6 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton6.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but6 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jButton7.getText() == "") {
            if (player1Turn == true) {
                jButton7.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but7 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton7.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but7 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (jButton8.getText() == "") {
            if (player1Turn == true) {
                jButton8.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but8 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton8.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but8 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (jButton9.getText() == "") {
            if (player1Turn == true) {
                jButton9.setText("X");
                player1Turn = false;
                jLabelInfoBar.setText("O's turn!");
                but9 = 'x';
                if (playerXWin() == true) {
                    playerXScore += 1;
                    jLabelXScore.setText(String.valueOf(playerXScore));
                    jLabelInfoBar.setText("X WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                } else {
                    if (SinglePlayerMode) {
                        computerGo();
                    }
                }
                changeButtonColor();
            } else {
                jButton9.setText("O");
                player1Turn = true;
                jLabelInfoBar.setText("X's turn!");
                but9 = 'o';
                if (playerOWin() == true) {
                    playerOScore += 1;
                    jLabelOScore.setText(String.valueOf(playerOScore));
                    jLabelInfoBar.setText("O WINS!");
                    disableButtons();
                    changeFirstPlayer();
                } else if (full() == true) {
                    jLabelInfoBar.setText("TIE!");
                    disableButtons();
                    changeFirstPlayer();
                    playerTScore += 1;
                    jLabelTScore.setText(String.valueOf(playerTScore));
                }
                changeButtonColor();
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton1PStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1PStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButton1PStateChanged

    private void jRadioButton1PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1PActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2P.isSelected()) {
            competitiveMode = false;
            jCheckBox1.setEnabled(true);
            jCheckBox1.setSelected(false);
            jRadioButton2P.setSelected(false);
            jRadioButton1P.setSelected(true);
            jButtonReset.doClick();
            SinglePlayerMode = true;
        } else {
            competitiveMode = false;
            jCheckBox1.setEnabled(true);
            jCheckBox1.setSelected(false);
            jRadioButton2P.setSelected(false);
            jRadioButton1P.setSelected(true);
            jButtonReset.doClick();
            SinglePlayerMode = true;
        }
    }//GEN-LAST:event_jRadioButton1PActionPerformed

    private void jRadioButton2PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2PActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1P.isSelected()) {
            competitiveMode = false;
            jCheckBox1.setEnabled(false);
            jCheckBox1.setSelected(false);
            jRadioButton1P.setSelected(false);
            jRadioButton2P.setSelected(true);
            jButtonReset.doClick();
            SinglePlayerMode = false;
        } else {
            competitiveMode = false;
            jCheckBox1.setEnabled(false);
            jCheckBox1.setSelected(false);
            jRadioButton1P.setSelected(false);
            jRadioButton2P.setSelected(true);
            jButtonReset.doClick();
            SinglePlayerMode = false;
        }
    }//GEN-LAST:event_jRadioButton2PActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            competitiveMode = true;
        } else {
            competitiveMode = false;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * This method checks to see if there has been a draw.
     *
     * @return if the board is full but no winner.
     */
    public static boolean full() {
        if (but1 != '\u0000' && but2 != '\u0000' && but3 != '\u0000'
                && but4 != '\u0000' && but5 != '\u0000' && but6 != '\u0000'
                && but7 != '\u0000' && but8 != '\u0000' && but9 != '\u0000') {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method checks to see if X won this round
     *
     * @return if X has won
     */
    public static boolean playerXWin() {
        if (but1 == 'x' && but2 == 'x' && but3 == 'x'
                || but4 == 'x' && but5 == 'x' && but6 == 'x'
                || but7 == 'x' && but8 == 'x' && but9 == 'x'
                || but1 == 'x' && but4 == 'x' && but7 == 'x'
                || but2 == 'x' && but5 == 'x' && but8 == 'x'
                || but3 == 'x' && but6 == 'x' && but9 == 'x'
                || but1 == 'x' && but5 == 'x' && but9 == 'x'
                || but7 == 'x' && but5 == 'x' && but3 == 'x') {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method checks to see if O won this round
     *
     * @return if O has won
     */
    public static boolean playerOWin() {
        if (but1 == 'o' && but2 == 'o' && but3 == 'o'
                || but4 == 'o' && but5 == 'o' && but6 == 'o'
                || but7 == 'o' && but8 == 'o' && but9 == 'o'
                || but1 == 'o' && but4 == 'o' && but7 == 'o'
                || but2 == 'o' && but5 == 'o' && but8 == 'o'
                || but3 == 'o' && but6 == 'o' && but9 == 'o'
                || but1 == 'o' && but5 == 'o' && but9 == 'o'
                || but7 == 'o' && but5 == 'o' && but3 == 'o') {
            return true;
        } else {
            return false;
        }
    }

    /**
     * The Main Method.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTT().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInfoBar;
    private javax.swing.JLabel jLabelOScore;
    private javax.swing.JLabel jLabelTScore;
    private javax.swing.JLabel jLabelXScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1P;
    private javax.swing.JRadioButton jRadioButton2P;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
